/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import model.User;

/**
 *
 * @author Storie
 */
public class StatisticMenuFrm extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(StatisticMenuFrm.class.getName());
    private User user;
    
    /**
     * Creates new form StatisticMenuFrm
     * @param user
     */
    public StatisticMenuFrm(User user) {
        this.user = user;
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        btnViewLeaderboard = new javax.swing.JButton();
        btnViewEloStats = new javax.swing.JButton();
        btnReturn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        jLabel1.setText("Thống kê");

        btnViewLeaderboard.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnViewLeaderboard.setText("Bảng xếp hạng");
        btnViewLeaderboard.addActionListener(this::btnViewLeaderboardActionPerformed);

        btnViewEloStats.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnViewEloStats.setText("Thống kê thay đổi Elo");
        btnViewEloStats.addActionListener(this::btnViewEloStatsActionPerformed);

        btnReturn.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnReturn.setText("Quay lại");
        btnReturn.addActionListener(this::btnReturnActionPerformed);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(113, 113, 113)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnViewEloStats, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnViewLeaderboard, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnReturn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(122, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(jLabel1)
                .addGap(45, 45, 45)
                .addComponent(btnViewLeaderboard)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnViewEloStats)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnReturn)
                .addContainerGap(98, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnViewLeaderboardActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnViewLeaderboardActionPerformed

    }//GEN-LAST:event_btnViewLeaderboardActionPerformed

    private void btnViewEloStatsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnViewEloStatsActionPerformed
        (new EloStatsFrm(user)).setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnViewEloStatsActionPerformed

    private void btnReturnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnReturnActionPerformed
        (new OrganizerHomeFrm(user)).setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnReturnActionPerformed



    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnReturn;
    private javax.swing.JButton btnViewEloStats;
    private javax.swing.JButton btnViewLeaderboard;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
